solve parsing issue

diff --git a/.github/workflows/Release.yml b/.github/workflows/Release.yml
--- a/.github/workflows/Release.yml
+++ b/.github/workflows/Release.yml
@@ -41,11 +41,24 @@ jobs:
       - name: Get Version and Tag From Code
         id: set_ver
         run: |
-          content=$(cat ${{ github.workspace }}/ART_PACKAGE/appsettings.json)
-          version=$(echo $content | jq -r '.Version')
-          release_name=$(echo $content | jq -r '.ReleaseName')
-          echo "VERSION=$version" >> $GITHUB_ENV
-          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV
+            content=$(cat ${{ github.workspace }}/ART_PACKAGE/appsettings.json)
+    
+            # Debugging: Output the content of appsettings.json
+            echo "Content of appsettings.json:"
+            echo "$content"
+    
+            # Try parsing the JSON content
+            version=$(echo "$content" | jq -r '.Version' || echo "Invalid JSON")
+            release_name=$(echo "$content" | jq -r '.ReleaseName' || echo "Invalid JSON")
+    
+            # Check for parsing errors
+            if [ "$version" = "Invalid JSON" ] || [ "$release_name" = "Invalid JSON" ]; then
+             echo "Error: Failed to parse appsettings.json."
+             exit 1
+            fi
+    
+            echo "VERSION=$version" >> $GITHUB_ENV
+            echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV
 
       - name: Check for existing release
         id: check_release
